services:
  readme-agent:
    build: ./Readme_Agent
    env_file:
      - .env

  agent-assistant:
    build: ./Agent_Assistant
    env_file:
      - .env
    stdin_open: true
    tty: true

  multi-agents:
    build: ./Multi_Agents
    env_file:
      - .env
    stdin_open: true
    tty: true
